using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SourceGenerators;

[Generator]
public class SettingsGenerator : IIncrementalGenerator
{
    private const string ConfigFileName = "app.config";
    private const string SettingsElementName = "Universal_x86_Tuning_Utility.Properties.Settings";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Watch for app.config in AdditionalFiles
        var configFiles = context.AdditionalTextsProvider
            .Where(file =>
                Path.GetFileName(file.Path).Equals(ConfigFileName, StringComparison.OrdinalIgnoreCase));

        context.RegisterSourceOutput(configFiles, (productionContext, additionalFile) =>
        {
            var fileText = additionalFile.GetText(productionContext.CancellationToken);
            if (fileText is null) return;

            var content = fileText.ToString();
            if (string.IsNullOrWhiteSpace(content)) return;

            try
            {
                var doc = XDocument.Parse(content);

                // Find the <userSettings> -> <SettingsElementName> -> <setting> elements
                var settingElements = doc.Descendants("userSettings")
                    .Descendants(SettingsElementName)
                    .Elements("setting");

                if (!settingElements.Any())
                    return;

                var sourceCode = GenerateSettingsClass(settingElements);
                productionContext.AddSource("Settings.g.cs", SourceText.From(sourceCode, Encoding.UTF8));
            }
            catch (Exception ex)
            {
                var descriptor = new DiagnosticDescriptor(
                    id: "CONFIG001",
                    title: "Config processing error",
                    messageFormat: $"Error processing {ConfigFileName}: {{0}}",
                    category: "Configuration",
                    defaultSeverity: DiagnosticSeverity.Error,
                    isEnabledByDefault: true);

                productionContext.ReportDiagnostic(Diagnostic.Create(
                    descriptor,
                    Location.None,
                    ex.Message));
            }
        });
    }

    private string GenerateSettingsClass(IEnumerable<XElement> settings)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Universal_x86_Tuning_Utility.Properties;");
        sb.AppendLine();
        sb.AppendLine("public sealed partial class Settings");
        sb.AppendLine("{");
        sb.AppendLine();

        foreach (var setting in settings)
        {
            var name = setting.Attribute("name")?.Value;
            var type = setting.Attribute("type")?.Value;

            if (string.IsNullOrEmpty(name)) continue;

            sb.AppendLine($@"
    public {type} {name}
    {{
        get => Get<{type}>(nameof({name}));
        set => Set(nameof({name}), value);
    }}");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }
}